MODEL_ID : 'gemma2-9b-it'
MASTER_DB_PATH : "C:/Users/HP/Programs/Projects/matrix-hackathon/chromadb_storage/master_db"
CHILD_DB_PATH : "C:/Users/HP/Programs/Projects/matrix-hackathon/chromadb_storage/conversation_db"